version: "3.8"

services:
  mariadb:
    build:
      context: ./requeriments/mariadb
      dockerfile: Dockerfile
    image: mariadb:latest
    restart: always
    networks:
      - backend_net
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
  # More services here ----->

networks:
  backend_net:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sadoming/data/volumes/mariadb_data

# Using the passwords saved in /secrets...
#  Note todo later: Maybe i can save that secrets on my github using the secrets label?
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
