version: "3.8"

services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    networks:
      - backend_net
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - backend_net
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_PORT: ${WORDPRESS_DB_PORT}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - backend_net
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

networks:
  backend_net:

volumes:
  mariadb_data: {}
  wordpress_data: {}

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
