services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    environment:
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sadoming/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sadoming/data/wordpress

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
