[client]
default-character-set = utf8mb4

[mysqld]
user = mysql

# Listen on all interfaces
bind-address = 0.0.0.0
port = 3306

pid-file = /run/mysqld/mysqld.pid
datadir = /var/lib/mysql
socket = /var/run/mysqld/mysqld.sock
log_error = /var/log/mysql/error.log

character-set-server = utf8mb4
collation-server = utf8mb4_general_ci

# Critic config for conectivity
skip_name_resolve = 1
skip-host-cache
skip-networking = 0

[mysqldump]
quick
quote-names

[mysql]

[mysqld_safe]
log-error=/var/log/mysql/error.log
pid-file=/var/run/mysqld/mysqld.pid

!includedir /etc/mysql/conf.d/
