[mysqld]
user = mysql
port = 3306
datadir = /var/lib/mysql
socket = /run/mysqld/mysqld.sock
pid-file = /run/mysqld/mysqld.pid
bind-address = 0.0.0.0
skip-name-resolve

# Configuraciones de seguridad
local-infile = 0
symbolic-links = 0
skip-host-cache

# Configuraciones de rendimiento
key_buffer_size = 256M
max_allowed_packet = 256M
thread_stack = 256K
thread_cache_size = 8
max_connections = 100

# Logs
log_error = /var/log/mysql/error.log

[mysql]
default-character-set = utf8mb4

[mysqldump]
max_allowed_packet = 256M
